name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOMAIN: app.proptuna.com

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build --build-arg DOMAIN=$DOMAIN -t app-image:latest .
          docker save app-image:latest > app-image.tar

      - name: Deploy to Digital Ocean
        env:
          PRIVATE_KEY: ${{ secrets.TUNA_SSH}}
          HOST: ${{ secrets.TUNA_HOST }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          # SCP directly to the expanded volume
          scp -o StrictHostKeyChecking=no -i private_key app-image.tar root@$HOST:/mnt/volume_nyc1_02/app-image.tar
          ssh -o StrictHostKeyChecking=no -i private_key root@$HOST '
            cd /mnt/volume_nyc1_01 && \
            docker load < app-image.tar && \
            docker stop app || true && \
            docker rm app || true && \
            docker run -d \
              --name app \
              --restart always \
              -p 8000:8000 \
              -e DOMAIN='$DOMAIN' \
              -e NODE_ENV=production \
              -v /mnt/volume_nyc1_01:/app/data \
              app-image:latest && \
            docker system prune -a --volumes -f
          '
